spring :
  application:
    name: comment
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true


server:
  servlet:
    encoding:
      force: true  # ?? ?? ?? ??


